<p>Pour sa premi&egrave;re &eacute;dition, le BAM Festival collabore avec 2 sites culturels li&eacute;geois incontournables - <em>L&rsquo;Acad&eacute;mie des Beaux-Arts de Li&egrave;ge</em> et <em>Le Cadran</em> - mais aussi avec une structure de renom international en mati&egrave;re d&rsquo;arts num&eacute;riques : <em>le Mapping Festival</em> de Gen&egrave;ve. Le BAM Festival propose un panel d&rsquo;activit&eacute;s s&rsquo;&eacute;talant sur 4 jours : installations sur des sites centriques de la ville de Li&egrave;ge ; performances live d&rsquo;artistes internationaux en premi&egrave;re exclusivit&eacute; belge ; workshops avec un artiste belge de renom, conf&eacute;rences et tables de discussion avec des professionnels du secteur des arts num&eacute;riques ; etc...<br />
Avec sa programmation de renom, ses diff&eacute;rents partenaires, sa vari&eacute;t&eacute; d&rsquo;activit&eacute;s, et son emplacement centrique, le BAM Festival se veut un festival ouvert &agrave; un large public. Toute personne avide de culture s&rsquo;y retrouvera. Il n&rsquo;est pas question de cibler les avertis d&rsquo;arts num&eacute;riques ni de vulgariser cette discipline artistique pour plaire aux novices. La programmation du festival permet &agrave; chacun d&rsquo;&eacute;changer, de d&eacute;couvrir, d&rsquo;&ecirc;tre interpel&eacute; tout simplement. Nous souhaitons dynamiser la sc&egrave;ne des arts num&eacute;riques en R&eacute;gion Li&eacute;geoise mais aussi &agrave; plus haute &eacute;chelle : en Belgique.</p>

<h2>PLUS EN DETAILS...</h2>
Le festival d&eacute;bute le <em>mardi 30 septembre 2013 &agrave; l&rsquo;Acad&eacute;mie Royale des Beaux Arts de Li&egrave;ge</em> &ndash; lieu centrique de la ville, o&ugrave; se tiendra l&rsquo;exposition majeure du festival. Au programme pour l&rsquo;inauguration : 4 performances live des artistes 1024 Architecture, CENC, Rythme/Vision et Nonotak personnalit&eacute;s de renom international et jamais produites en Belgique. Il s&rsquo;agit l&agrave; de 4 exclusivit&eacute; belge !<br />
Du <em>mercredi 1er au jeudi 2 octobre</em> se d&eacute;roule un workshop tenus par Mike Latona. L&rsquo;aboutissement de ces ateliers sera diffus&eacute; lors de la soir&eacute;e de cl&ocirc;ture du festival &agrave; la Rotonde.<br />
Le jeudi 2 octobre est plac&eacute; sous le signe de l&rsquo;&eacute;change. S&rsquo;y tiendront <em>3 conf&eacute;rences</em> avec des professionnels du secteur des arts num&eacute;riques, une table ronde avec les artistes programm&eacute;s et en cl&ocirc;ture une performance audio-vid&eacute;o live des 1024 Architecture.<br />
Le festival se cl&ocirc;ture <em>le vendredi 3 octobre au Cadran</em>. Lieu festif de Li&egrave;ge par excellence, son espace modulable sera le site parfait pour allier les arts num&eacute;riques et la musique de mani&egrave;re spectaculaire. Le choix de la programmation musicale est laiss&eacute; &agrave; l&rsquo;&eacute;quipe de NoName, un autre partenaire de l&rsquo;&eacute;v&egrave;nement. Les performances d&rsquo;arts num&eacute;riques live seront le fruit du travail du workshop et de divers installations d&rsquo;artistes belges ainsi que 2 Vj&rsquo;ette Polonaise Vj Jago et Vj Emiko avec une performance audio/video. Un stage design unsiant le Led, Lazer, mapping sera r&eacute;alis&eacute; par le collectif Belgo/suisse Fool Control.</p>

<p>
Le Bam Festival c&rsquo;est <em>20 artistes, dont 12 internationaux, 4 performances, 3 conf&eacute;rences, un workshop</em>, une expo, des installations, du mapping, du led, des esprits cr&eacute;atif &hellip; et la pr&eacute;sentation d&rsquo;un nouveau logiciel Open source Belgo/ Canadien : <em>MapMap<</em>.</p>

<p>Nous sommes fier d&rsquo;inviter les cr&eacute;ateurs des deux logiciels far du mapping et vj&rsquo;ing, MadMapper et Modul8, ainsi que la Dream Team du Mapping Festival de Gen&egrave;ve.&nbsp;<br />
Une programmation de qualit&eacute; et l envie de communique&nbsp;</p>

